### ISSUE TITLE
npm install失败

### ISSUE THREAD

**Issue by mishengqiang** [tolking/vuepress-theme-ououe#20]
npm安装失败，提示没有发现该项目依赖vuepress-plugin-blog-multidir@^1.0.5的版本，我看了一下npm仓库中vuepress-plugin-blog-multidir的最新版本为1.0.4。
npm的注册源是国内的淘宝镜像

**Comment by tolking** [comment]
是淘宝镜像版本同步失败，使用 npm i vuepress-plugin-blog-multidir -s 而不是 cnpm

**Comment by mishengqiang** [comment]
我用的就是`npm`，但是注册源我换成了淘宝的。我已经使用yarn安装解决了。谢谢 @tolking
