### ISSUE TITLE
关于出现The node to be removed is not a child of this node

### ISSUE THREAD

**Issue by zzzttt1017** [tolking/vuepress-theme-ououe#21]
![image](https://user-images.githubusercontent.com/12960467/76141220-17951680-609d-11ea-8999-f16865eff192.png)
你好，我在基于您的主题开发并添加了自己的组件后，生产环境控制台报错了，在尝试了一些办法后没有解决掉，查了下你这边有做这个处理，我想知道这个问题出现的原因跟处理的原理，以便我理解这个问题并解决，请问您方便告诉我么？

**Comment by tolking** [comment]
vuepress的版本不同有的报错，有的不
建议你先升级vuepress的版本到最新版
这里主要是分开开发与生产引用的组件

**Comment by zzzttt1017** [comment]
> vuepress的版本不同有的报错，有的不
> 建议你先升级vuepress的版本到最新版
> 这里主要是分开开发与生产引用的组件

好的，感谢回复，刚试着更新到最新版本依然有问题，下一步我会尝试阅读下源码
