### ISSUE TITLE
当安装最新版本的Vuepress 1.3.1时，lastUpdated会出现Invalid Date

### ISSUE THREAD

**Issue by mishengqiang** [tolking/vuepress-theme-ououe#22]
Vuepress 1.3.1版本中的`@vuepress/plugin-last-updated`插件新增了[默认转换函数](https://github.com/vuejs/vuepress/issues/2168)，导致当`lang: zh-CN`时该主题中的`this.$page.lastUpdated`二次转换出现错误`Invalid Date`。
![日期进行了多次toLocaleString转换](https://user-images.githubusercontent.com/9413032/76288558-f2ddb080-62e1-11ea-8271-1a320f64373e.png)

**Comment by tolking** [comment]
我后面会做兼容处理
可以通过在你的 config.js 设置 last-updated 的默认值覆盖 [参考 第二条](https://ououe.com/posts/2019/07/07/vuepress/)
