### ISSUE TITLE
建议使用$withBase()处理一下绝对路径

### ISSUE THREAD

**Issue by mishengqiang** [tolking/vuepress-theme-ououe#23]
当config.js文件中的`base`设置为非`/`值时，且`themeConfig.cover`和markdown文件中的$frontmatter.image的值是绝对路径，则编译后会图片路径会出错。
**建议使用`$withBase()`处理一下。**
[参考文档](https://vuepress.vuejs.org/zh/guide/assets.html#%E5%9F%BA%E7%A1%80%E8%B7%AF%E5%BE%84)

**Comment by tolking** [comment]
关于这个 欢迎 pr

**Comment by tolking** [comment]
这个我在想会不会通过 img-lazy 处理会更好一些，同时处理主题与mark down的图片。我周末测试一下

**Comment by tolking** [comment]
done
