### ISSUE TITLE
HTML webpack plugin issues

### ISSUE THREAD

**Issue by raisty** [tolking/vuepress-theme-ououe#27]
I tried theme with the latest Vuepress (`^1.6.0`) and Yarn v `1.22.4`.
After `yarn install` and `yarn dev` which is: `vuepress dev blog` I am getting:

```
Html Webpack Plugin:

  TypeError: Cannot read property '0' of undefined
  
  - index.js:14 exports.normalizeHeadTag
    [blog]/[@vuepress]/core/lib/node/util/index.js:14:22
  
  - HeadPlugin.js:23 tags.forEach.tag
    [blog]/[@vuepress]/core/lib/node/webpack/HeadPlugin.js:23:28
  
  - Array.forEach
  
  - HeadPlugin.js:22 compilation.hooks.htmlWebpackPluginAlterAssetTags.tapAsync
    [blog]/[@vuepress]/core/lib/node/webpack/HeadPlugin.js:22:21
  
  
  - new Promise
  
  
  - Hook.js:154 AsyncSeriesWaterfallHook.lazyCompileHook
    [blog]/[tapable]/lib/Hook.js:154:20
  
  - index.js:673 
    [blog]/[vuepress-html-webpack-plugin]/index.js:673:47
  
  - index.js:187 Promise.resolve.then.then.then.then.then.then.then.result
    [blog]/[vuepress-html-webpack-plugin]/index.js:187:18
  
  - task_queues.js:86 processTicksAndRejections
    internal/process/task_queues.js:86:5
```

**Comment by tolking** [comment]
I need a demo

**Comment by tolking** [comment]
Or reference [vuepress-theme-ououe-template](https://github.com/tolking/vuepress-theme-ououe-template)

**Comment by raisty** [comment]
I overcome this issue, with reinstallation.

For reference, I am attaching a workaround on how to overcome the issue.

1. `mkdir demo && cd demo`
1. `yarn create vuepress-site`
1. `cd docs`
1. `yarn add vuepress-theme-ououe -D`
1. `yarn install`
1. Setup theme in docs/src/.vuepress/config.js `theme: 'ououe',`
1. `yarn dev`
1. Open http://localhost:8080/

Seems working after changes. If the problem will happen, I will open the next issue.

Thank you.
