### ISSUE TITLE
Custom containers not working

### ISSUE THREAD

**Issue by MindMansion** [tolking/vuepress-theme-ououe#29]
The custom containers seems to be broken and doesn't work.

**Comment by tolking** [comment]
If you mean this:

```md
::: tip
This is a tip
:::
```

[vuepress-plugin-container](https://www.npmjs.com/package/vuepress-plugin-container) have been removed from the vuepress core code for a long time. You need to install it ([reference](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/index.js#L30))

**Comment by MindMansion** [comment]
Oh I see! Thanks
