### ISSUE TITLE
Can we modify some place by our idea？

### ISSUE THREAD

**Issue by linsicong003** [tolking/vuepress-theme-ououe#9]
I love your design !!! appreciated what you do in this project. But I want a little different to the offical version in my blog, so can I modify the css or js in this theme?

If I can do it, expect copy all your code and use it in a original way, how can I customize my own version in a elegant way?

**Comment by tolking** [comment]
1. `.vuepress/theme`[Writing a theme](https://v1.vuepress.vuejs.org/theme/writing-a-theme.html)
2. [Theme Inheritance](https://v1.vuepress.vuejs.org/theme/inheritance.html)
3. fork then pull requests(!?) or modified to a new theme 
 ...
